spring:
  r2dbc:    url: r2dbc:postgresql://localhost:5432/Order 
    username: Order
    password: order1111
  messages:    basename: i18n/messages
#    encoding: UTF-8
    

logging:
  level:    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    org.springframework.http.codec : DEBUG
#    org.springframework.security.web.server.authorization.DelegatingReactiveAuthorizationManager : DEBUG 
#    org.springframework.security : DEBUG
#    reactor.netty.http.client : DEBUG

api:
  baseUri:
    lotteon: https://pbf.lotteon.com
    
jjwt:
  password:
    encoder:
      secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
      salt: secret
      iteration: 33
      keylength: 256  
      expiration: 86400 #60 * 60
      